theme: jekyll-theme-minimal
title: I4S* : Industry 4.0 for the Smart-*
description: A project investigating resilience and weaknesses of Smart-* system-of-systems architectures
google_analytics: G-SRDJC3VTCC
